swagger: '2.0'
info:
  version: '1.0'
  title: Tutor service API
basePath: '/'
consumes:
  - application/json
  - application/vnd.api+json
produces:
  - application/json
  - application/vnd.api+json

paths:
  /test:
    get:
      description: Test route
      handler: 'testDatabaseConnection'
      responses:
        200:
          description: OK

  /test/error:
    get:
      description: Test error handling
      handler: 'testErrorResponse'
      responses:
        400:
          description: Basic error

definitions:
